workspace:
  base: /go
  path: src/github.com/drone-demos/drone-with-go

pipeline:
  test:
    image: golang:latest
    commands:
      - echo test9
      # - go vet
      # - go test -v -cover
  build:
    image: golang:latest
    commands:
      - pwd
      - ls
      - echo build-34
      # - go build
